"""Budget suggestion and persistence, based on historic transaction data.

`suggest_budget` averages actual spend per category over a trailing window
of calendar months -- a starting point to edit, not a prescription. The
saved budget (config/budget.yaml, gitignored -- unlike rules.yaml/
categories.yaml, this holds real derived spending figures, not just
category names/patterns) is a flat category -> monthly amount mapping,
loaded by `report budget` to compare against actual spend for a given
month.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from sqlite3 import Connection

import yaml

# Credit Card Payment is an internal transfer (paying off a card from a
# current account) -- the real spend it represents is already counted once
# under whatever category the card purchases themselves fall into.
# Including it too would double-count that spend in a suggested budget.
DEFAULT_EXCLUDE_CATEGORIES = ("Credit Card Payment",)


def _months_before(d: date, months_back: int) -> date:
    month = d.month - months_back
    year = d.year
    while month <= 0:
        month += 12
        year -= 1
    return date(year, month, 1)


def suggest_budget(
    conn: Connection,
    months: int = 3,
    exclude_categories: tuple[str, ...] = DEFAULT_EXCLUDE_CATEGORIES,
    as_of: date | None = None,
) -> dict:
    """Per-category monthly spend average over the trailing `months`
    calendar months, counting from the 1st of the month `months` back from
    `as_of` (default: today).
    """
    as_of = as_of or date.today()
    start = _months_before(as_of, months)

    if exclude_categories:
        placeholders = ",".join("?" for _ in exclude_categories)
        exclude_clause = f"AND category NOT IN ({placeholders})"
    else:
        exclude_clause = ""

    rows = conn.execute(
        f"""
        SELECT category, SUM(-amount) AS total, COUNT(*) AS n
        FROM transactions
        WHERE date >= ? AND amount < 0 {exclude_clause}
        GROUP BY category
        ORDER BY total DESC
        """,
        (start.isoformat(), *exclude_categories),
    ).fetchall()

    return {
        "start_date": start.isoformat(),
        "months": months,
        "categories": [
            {
                "category": r["category"],
                "total": r["total"],
                "monthly_average": r["total"] / months,
                "transaction_count": r["n"],
            }
            for r in rows
        ],
    }


def load_budget(budget_path: Path) -> dict[str, float]:
    if not budget_path.exists():
        return {}
    data = yaml.safe_load(budget_path.read_text()) or {}
    return dict(data.get("budget", {}))


def save_budget(budget_path: Path, budget: dict[str, float]) -> None:
    budget_path.parent.mkdir(parents=True, exist_ok=True)
    body = {"budget": {k: round(v, 2) for k, v in sorted(budget.items())}}
    header = (
        "# Monthly budget per category, in the same units as your\n"
        "# transactions (pounds). Generated by `money budget suggest\n"
        "# --save`, or edit by hand. Gitignored -- these numbers are\n"
        "# derived from your real spending. Compare against actual spend\n"
        "# with:\n"
        "#   python -m money.cli report budget --month YYYY-MM\n"
    )
    budget_path.write_text(header + yaml.safe_dump(body, default_flow_style=False, sort_keys=False))
